# This section explicitly tells Nixpacks which system packages to install.
[phases.setup]
nixPkgs = ["python311", "gcc"]

# This section now uses the absolute path to the python we just installed
# to guarantee we are using the correct one with pip.
[phases.install]
cmds = [
    "/nix/var/nix/profiles/default/bin/python -m pip install --upgrade pip",
    "/nix/var/nix/profiles/default/bin/python -m pip install -r requirements.txt"
]

# The start command also uses the absolute path for maximum robustness.
[start]
cmd = "/nix/var/nix/profiles/default/bin/python -m uvicorn main:app --host 0.0.0.0 --port $PORT"